trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: InstallBoto3
  jobs:
  - job: InstallBoto3
    steps:
    - script: pip install boto3
      displayName: 'Install boto3'
    
    - script: python -c "import boto3; print('Boto3 installed successfully')"
      displayName: 'Test boto3 installation'
